/*
    Copyright 2021 Exclamation Labs
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
        http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/
package com.exclamationlabs.connid.base.config.plugin.model

class Service extends ConfigurationGroup {
    @Override
    List<String> getYamlPath() {
        ['service']
    }

    @Override
    Set<ConfigurationItem> getConfigurationItems() {
        [
            new ConfigurationItem.Builder()
                    .name('serviceUrl', getYamlPath())
                    .order(1201)
                    .required(true)
                    .displayText('Service URL')
                    .helpText('The base service URL for the API this connector' +
                    ' needs to access to get or store data.')
                    .type(ConfigurationItemType.STRING).build(),
            new ConfigurationItem.Builder()
                    .name('duplicateErrorReturnsId', getYamlPath())
                    .order(1202)
                    .required(false)
                    .defaultValue('false')
                    .displayText('Duplicate Error Returns Id')
                    .helpText('When a create is attempted and an AlreadyExistsException is' +
                            ' generated by the driver/invocator, the adapter shall attempt' +
                            ' to call getOneByName() driver/invocator method to return the' +
                            ' id of the existing record matching the current name value.')
                    .type(ConfigurationItemType.BOOLEAN).build()
        ] as Set<ConfigurationItem>
    }

    @Override
    String getConfigurationInterface() {
        getBaseTypesPackage() + '.ServiceConfiguration'
    }
}
